### ISSUE TITLE
Support the type "float" in ra-api-?.dtd

### ISSUE THREAD

**Issue by canardleteer** [ClusterLabs/resource-agents#1259]
I have got a use case for a parameter of type `float`.

While I can encode this in a `string` for now, I could also do a PR for a change [here](https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/ra-api-1.dtd#L30). I am hesitant to propose changing a versioned contract that hasn't changed in close to 9 years. I am also hesitant to propose making a new major version contract for such a tiny change.

Would it be reasonable to propose `ra-api-1-1.dtd` or is there a larger `ra-api-2.dtd` effort in the works that I could append my desired change to?

**Comment by jnpkrn** [comment]
Agreed that OCF-spec is the right target.

Please not that any addition will require a decent amount of
deliberation, since what you may see behind a generic `float`
(likely raising a simplest idea of numbers like `1.24` in your
mind) shall rather be a rigorously defined data type; consider:

- are plus/minus infinity values allowed? how to express them
  lexically?

- are exponent forms allowed?  how to express them lexically?

- what are the actual numeric constraints wrt. preciseness?
  (compare `float` vs. `double` data types in C standard)

- ...

- last but not least: how does it combine with existing
  treatments of the very abstracted numeric data types
  elsewhere (said C standard, XML schema datatypes, etc.)

You can see this starts to be convoluted pretty fast.
But a standard like OCF needs to deal with all these details
for it to be useful, a definite answer, after all.
Brain-absenting simplest additions would make just for further
erosion down the road.

**Comment by canardleteer** [comment]
I agree adding `float` isn't as simple as just adding `float`, what makes it even more difficult, is where that parameter gets put into use, since it can be fed downstream to an unlimited number of recipient types, each with their own notion of `float`/`double`/`decimal`.

I'll think about it a little more and make an issue over in OCF-spec when I get a chance.

Closing this one. Thanks for pointing me over to the spec work!
