### ISSUE TITLE
pgsql: check for running wal receiver process is not compatible with PostgreSQL 12

### ISSUE THREAD

**Issue by antaflos** [ClusterLabs/resource-agents#1551]
In https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/pgsql#L937 the process table is checked for a running WAL receiver process by means of `grep "[w]al receiver process"`. This doesn't work for PostgreSQL 12 (and possibly 11), because the WAL receiver process now goes by the name of `walreceiver` instead of `wal receiver process`.

A check that is compatible with all PostgreSQL versions looks like this:

```
receiver_parent_pids=`ps -ef | tr -s " " | grep "[w]al\s*receiver" | cut -d " " -f 3`
```

I will submit a PR to address this issue.

**Comment by oalbrigt** [comment]
Sounds good to me. Make sure there arent any other "wal receiver" messages that could get matched when it shouldnt.

**Comment by ShunKawano** [comment]
In PostgreSQL-12, if you are using pgsql Resource Agent published on GitHub and set to the option "check_wal_receiver='true‘. The pacemaker.log prints 
`“Warning: wal receiver process is not running”` every 4-5 seconds 

The resource agent function pgsql_wal_receiver_status()  searches for the process name [wal receiver process] and determines the Process ID for the wal_receiver working system. However, since the Process Name of the wal_receiver running in PostgreSQL-12 is [walreciever streaming] the corresponding Process ID cannot be indentified, leading to the output of the log. 

The resource agent function pgsql_wal_receiver_status()  searches for the process name [wal receiver process] and determines the Process ID for the wal_receiver working system.

**Comment by antaflos** [comment]
I had forgotten about this issue and my promise to submit a PR. But here it is now.
