### ISSUE TITLE
IPaddr2 IPv6 preferred_lft option

### ISSUE THREAD

**Issue by krig** [ClusterLabs/resource-agents#560]
Received this feature request for the IPaddr2 resource agent:

> Configure IPv6 address with option preferred_lft 0. This is required to mark the virtual ip as "deprecated" source address and thus to use only physical addresses. 

> See http://www.davidc.net/networking/ipv6-source-address-selection-linux

I don't know if this is actually something that you would want to do by default, but would it make sense to add an option to set this on the virtual IP? It seems to mostly make sense for IPv6.

**Comment by dmuhamedagic** [comment]
I don't find the preferred_lft option neither in the ip-address(8) man page nor in the rest of the iproute package. But I couldn't find an alternative way to set an address as deprecated.
@kskmori Keisuke-san, do you want to take a look?

**Comment by kskmori** [comment]
It was once requested in #68 and the conclusion is that it's preferable to use address labels instead of preferred_lft 0 for that purpose. 

So the solution would be either:
* enable lvs_ipv6_addrlabel option (introduced by #158 9b1c28c)
* or add an address label in the system configuration by doing something like:
```
ip addrlabel add prefix fd00:172:20:25::243 label 99
```

**Comment by krig** [comment]
Thank you for the clear explanation! Closing this.
