### ISSUE TITLE
Updates are overwriting config files

### ISSUE THREAD

**Issue by nrgeil** [ClusterLabs/resource-agents#612]
I had to make changes to the pgsql config file in /usr/lib/ocf/resource.d/heartbeat because PostgreSQL was installed to a different directory. After running a yum update, all the files are overwritten and all of my changes are lost. The database is then inaccessible until I go in and fix the files again.

**Comment by fabbione** [comment]
It would be useful to know how you are upgrading, distro, release, etc.

**Comment by nrgeil** [comment]
I'm running yum update. This is also the 3rd time this has happened and I just now realized what was happening.
CentOS release 6.6 (Final)
resource-agents x86_64 3.9.5-12.el6_6.5

**Comment by fabbione** [comment]
rpm does not preserve changes in those files because they are not marked configuration files. If you need a customized agent, the best path is to copy the agent under another name (PostgreSQL-custom) edit the name in the metadata to avoid conflicts with the rpm provided one, apply your fixes and use that in pacemaker configuration.

Another option would be to make the path to your instance of pgsql configurable in the shipped agent and have it as config option, so we can merge the change upstream and won't break across upgrades. At that point you would have it as config option when creating the resource.

Anyway this isn't a bug in resource-agents either per-se. If nothing we can expand the agent to include your customization as config options (given you can provide what's necessary).

**Comment by nrgeil** [comment]
Thanks for the feedback, I will make the necessary changes with my configuration.

In case you do want to expand the agent, PostgreSQL 9.3 has a different default install directory than previous versions. These are the changes I had to make:
From
OCF_RESKEY_pgctl_default=/usr/bin/pg_ctl
OCF_RESKEY_psql_default=/usr/bin/psql
OCF_RESKEY_pgdata_default=/var/lib/pgsql/data

To 
OCF_RESKEY_pgctl_default=/usr/pgsql-9.3/bin/pg_ctl
OCF_RESKEY_psql_default=/usr/pgsql-9.3/bin/psql
OCF_RESKEY_pgdata_default=/var/lib/pgsql/9.3/data

**Comment by fabbione** [comment]
All those options are already configurable when creating the resource.

<parameters>
<parameter name="pgctl" unique="0" required="0">
<longdesc lang="en">
Path to pg_ctl command.
</longdesc>
<shortdesc lang="en">pgctl</shortdesc>
<content type="string" default="${OCF_RESKEY_pgctl_default}" />
</parameter>

<parameter name="psql" unique="0" required="0">
<longdesc lang="en">
Path to psql command.
</longdesc>
<shortdesc lang="en">psql</shortdesc>
<content type="string" default="${OCF_RESKEY_psql_default}" />
</parameter>

<parameter name="pgdata" unique="0" required="0">
<longdesc lang="en">
Path to PostgreSQL data directory.
</longdesc>
<shortdesc lang="en">pgdata</shortdesc>
<content type="string" default="${OCF_RESKEY_pgdata_default}" />
</parameter>

Just set them when creating the resource and you are done.
