### ISSUE TITLE
The findif() function should be changed to calculate the broadcast address from the cidr netmask

### ISSUE THREAD

**Issue by krig** [ClusterLabs/resource-agents#656]
- An interface without any address configured yet:
```
cn2:~ # ip a show dev vlan4
10: vlan4@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 52:54:00:9f:d3:d5 brd ff:ff:ff:ff:ff:ff
cn2:~ # ip r show dev vlan4
```

- An IPaddr2 resource with the following parameters:
```
OCF_RESKEY_nic="vlan4"
OCF_RESKEY_ip="192.168.4.1"
OCF_RESKEY_cidr_netmask="24"
(OCF_RESKEY_broadcast is NOT set)
```

findif returns an empty broadcast in this case:
```
cn2:~ # . /usr/lib/ocf/lib/heartbeat/findif.sh
cn2:~ # findif
vlan4 netmask 24 broadcast
```

The findif binary works as expected:
```
cn2:~ # /usr/lib64/heartbeat/findif
vlan4   netmask 255.255.255.0   broadcast 192.168.4.255
```

The issue is, that findif reads the broadcast from an existing ip address in this subnet, if there is none, it fails.
This is a regression from the old behaviour and does not work as documented in the IPaddr2 metadata:

```
<parameter name="broadcast">
<longdesc lang="en">
Broadcast address associated with the IP. If left empty, the script will
determine this from the netmask.
</longdesc>
<shortdesc lang="en">Broadcast address</shortdesc>
<content type="string" default=""/>
</parameter>
```

The findif() function should be changed to calculate the broadcast address from the cidr netmask.

Also:

in findif.sh:
```
set -- `ip -o -f $family addr show | grep $7`
```

this is broken, because `$7` is the IP address returned by `ip -o -f $family route list match $match $scope`

problem 1: An IPv4 address contains dots, grep uses regex...

problem 2: if IP address is 10.1.1.1, it will also match 110.1.1.1 as a substring. The grep needs more context.

possible fix:

```
ip -o -f $family addr show | fgrep "$family $7/"
```

**Comment by kskmori** [comment]
> The issue is, that findif reads the broadcast from an existing ip address in this subnet, if there is none, it fails.

Could you elaborate what exactly "fails" means and the problem on your use case? 
I think that it is an intentional behavior to conform to the iproute (/sbin/ip) utility, that is, "brd is an optional, and will not be set unless an user specified explicitly." 

So the current IPaddr2 RA should work as follows:
- IPaddr2 will not assign the broadcast value unless the user specified it (as /sbin/ip does not)
- if the user specified it in the 'broadcast' parameter of the RA, then IPaddr2 will assign it
- if the broadcast was already configured on the existing subnet on the NIC, then IPaddr2 will try to pick and assign it

Yes, the first is a bit change from the old version, but practically it should change nothing and work as expected as before (only the visibility of /sbin/ip output changes).  Of course I may be missing something though. 
The meta-data description might need to be improved.

If we all agree on "should always assign the broadcast based on the netmask" (regardless of /sbin/ip behavior) then I'm fine with it.
In this case, giving brd '+' option for /sbin/ip  may be usable.
```
[root@devnode65 ~]# ip a s dev vlan2
7: vlan2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 52:54:00:65:00:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fe65:0/64 scope link 
       valid_lft forever preferred_lft forever
[root@devnode65 ~]# ip a a 192.168.4.1/24 brd "+" dev vlan2
[root@devnode65 ~]# ip a s dev vlan2
7: vlan2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 52:54:00:65:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.4.1/24 brd 192.168.4.255 scope global vlan2
    inet6 fe80::5054:ff:fe65:0/64 scope link 
       valid_lft forever preferred_lft forever
[root@devnode65 ~]# 
```

**Comment by krig** [comment]
If the current behavior is the desired one, I am fine with that and can convert this patch to only modify the parameter description. The main concern is a mismatch between the documented and actual behavior.

The problem description is from a customer. I will give your feedback to them and see what they say.

Thanks!

**Comment by dmuhamedagic** [comment]
On Thu, Aug 27, 2015 at 12:43:11AM -0700, Keisuke MORI wrote:
> In this case, giving brd '+' option for /sbin/ip  may be usable.
...
> [root@devnode65 ~]# ip a a 192.168.4.1/24 brd "+" dev vlan2

That looks good!

**Comment by krig** [comment]
Thanks for your comments, both of you! I am going to close this pull request.
