### ISSUE TITLE
Slapd: ocf_exit_reason: command not found

### ISSUE THREAD

**Issue by xtavras** [ClusterLabs/resource-agents#682]
I see often these messages in corosync log 
```
info: RA output: (SLAPD:0:monitor:stderr) /usr/lib/ocf/resource.d//custom/slapd: line 412: ocf_exit_reason: command not found
```
where line 412 is:
```
ocf_exit_reason "slapd process not found."
```
is it some bug?

**Comment by lge** [comment]
On Fri, Sep 18, 2015 at 02:50:16AM -0700, xtavras wrote:
> I see often these messages in corosync log 
> ```
> info: RA output: (SLAPD:0:monitor:stderr) /usr/lib/ocf/resource.d//custom/slapd: line 412: ocf_exit_reason: command not found
> ```
> where line 412 is:
> ```
> ocf_exit_reason "slapd process not found."
> ```
> is it some bug?

I don't think so.  It's a shell function defined along with all the
other ocf helper shell functions.

Did you try to grab the single resoruce agent,
and run it with an older installation?

If so, you'd probably need to simply declare a dummy function
ocf_exit_reason() { :; }

If not, then we need more information about what version this is,
how you installed it, and how you run it.

**Comment by xtavras** [comment]
Hi  @lge , sorry for late response.

I think I was not clear, I'm running this version https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/slapd (commit "db3e2e") on "debian wheezy" with stock pacemaker (1.1.7-1), as I understood the shell function doesn't work and pacemaker tries to run this like normal command. What another info do you need?

Thanks,
Stan

**Comment by lge** [comment]
On Thu, Oct 15, 2015 at 03:17:30AM -0700, xtavras wrote:
> Hi  @lge , sorry for late response.
> 
> I think I was not clear, I'm running this version
> https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/slapd
> (commit "db3e2e") on "debian wheezy" with stock pacemaker (1.1.7-1),
> as I understood the shell function doesn't work and pacemaker tries to
> run this like normal command. What another info do you need?

None.

If I understand correctly, you grabbed a single resource agent script,
and try to use it with an older resource-agents installation.

The resource agents project has since learned a few new helper
functions, and obviously resource agent scripts from more recent
commits will expect the framework to be complete.

If you "rip out" some single more recent script,
and want to use it with the older "infrastructure",
then you may or may not be lucky.

In this case, this more recent script expects a helper function
that your older infrastructure does not define yet.

Lucky for you, this one is only about diagnostics, not basic
functionality, so you could just define a dummy function instead.

Better yet, upgrade the full resource-agents package,
don't graft a single script from today into your old framework.

-- 
: Lars Ellenberg
: http://www.LINBIT.com | Your Way to High Availability
: DRBD, Linux-HA  and  Pacemaker support and consulting

DRBD� and LINBIT� are registered trademarks of LINBIT, Austria.

**Comment by xtavras** [comment]
Hi @lge ,

thank you for great explanation, so the solution will be to update "resource-agents" package which supports "ocf_exit_reason" function in "ocf-shellfuncs". I'll close the issue.

Best,
Stan
