### ISSUE TITLE
Postgres Master-role migration 

### ISSUE THREAD

**Issue by kunalija** [ClusterLabs/resource-agents#808]
Hi guys,

I have a postgres master/slave setup on SLES11SP3. For maintenance purpose I need a procedure to move the master role to the other node. I've tried the command 'crm_resource --resource msPostgresql --ban --master --host node1 --lifetime "P60S"'. Master role is actually moved to node2 but node1 stops with status disconnected (PGSQL.lock file remains in tmp directory). I have to manually delete the lock file and do a resource cleanup. Node1 should remain as slave after the master migration. Is it a bug or expected behaviour?
PS What is the recommended version of pgsql ra agent, the one shipped with SLES or the latest from git? 

Version: 1.1.11-3ca8c3b
Postgres 9.1

Thanks

**Comment by krig** [comment]
Well, first of all SLES11SP3 is getting quite old. Besides that, it sounds like this may be a problem of too short timeouts: Try increasing your operation timeouts and see if that helps.

**Comment by kunalija** [comment]
These are my current values. Tried timeout with 120s and different "interval" values, same result.

 primitive pgsql ocf:heartbeat:pgsql \
     params \
        pgctl="/usr/bin/pg_ctl" \
        psql="/usr/bin/psql" \
        pgdata="/var/lib/pgsql/data/" \
        start_opt="-p 5432" \
        rep_mode="sync" \
        node_list="db1 db2" \
        restore_command="/var/lib/pgsql/data/restore_wal %f %p" \
        primary_conninfo_opt="keepalives_idle=60 keepalives_interval=5 keepalives_count=5" \
        master_ip="192.168.5.100" \
        restart_on_promote="true" \
		op start   timeout="60s" interval="0s"  on-fail="restart" \
		op monitor timeout="60s" interval="4s" on-fail="restart" \
		op monitor timeout="60s" interval="3s"  on-fail="restart" role="Master" \
		op promote timeout="60s" interval="0s"  on-fail="restart" \
		op demote  timeout="60s" interval="0s"  on-fail="stop" \
		op stop    timeout="60s" interval="0s"  on-fail="block" \
		op notify  timeout="60s" interval="0s"

 primitive vip-master ocf:heartbeat:IPaddr2 \
     params \
         ip="192.168.5.100" \
         nic="eth0" \
         cidr_netmask="24" \
     op start   timeout="60s" interval="0s"  on-fail="stop" \
     op monitor timeout="60s" interval="10s" on-fail="restart" \
     op stop    timeout="60s" interval="0s"  on-fail="block" \
        meta target-role="Started"

**Comment by kskmori** [comment]
> Master role is actually moved to node2 but node1 stops with status disconnected (PGSQL.lock file remains in tmp directory). I have to manually delete the lock file and do a resource cleanup. Node1 should remain as slave after the master migration. Is it a bug or expected behaviour?

This is an expected behaviour, because PostgreSQL can not "demote" by its nature and it must always stop.

Remaining PGSQL.lock here is also by intention to let you know that a human intervention is required here;  you must take the basebackup from node2 (new master) to node1 (which may have outdated data) before restarting node1.

Without taking the basebackup, the old master node (node1) should fail to reconnect as a slave because the timeline ID does not match to the new master which has been increased when promoted. (this is a limitation in PostgreSQL 9.1 and until 9.2 at least)

**Comment by kskmori** [comment]
> Without taking the basebackup, the old master node (node1) should fail to reconnect as a slave because the timeline ID does not match to the new master which has been increased when promoted. (this is a limitation in PostgreSQL 9.1 and until 9.2 at least)

Ah, you have set restart_on_promote="true" which would avoid to happen this so please ignore this paragraph.

**Comment by kunalija** [comment]
> Remaining PGSQL.lock here is also by intention to let you know that a human intervention is required here; you must take the basebackup from node2 (new master) to node1 (which may have outdated data) before restarting node1.

Yes, but I would expect that the migrate command is a human intervention and migrating the master role is with intention, so why keep the lock file and not stop/start the old master as a standby.

**Comment by kskmori** [comment]
The reason behind is to eliminate a possible data corruption in
the scenario as described in the following slide, p.36.
* http://www.slideshare.net/takmatsuo/2012929-pg-study-16012253

It might not be affected only when you've migrate it by command
i.e. the old master has been stopped gracefully,
but it must be really hard to decide it in the RA reliably if a
new slave can restart safely or not because demote can be also
called in a variety of failure scenarios.

So the current best practice is
_"always restore the basebackup before start a new slave"_,
which is for the data integrity, and also good for simplifying
the rule of operations.
