### ISSUE TITLE
Route agent failed when adding default IPv6 route

### ISSUE THREAD

**Issue by Jean-Daniel** [ClusterLabs/resource-agents#996]
Actually, the Route agent uses the 'OCF_RESKEY_destination' key to detect the `addr_family`

Unfortunately, when adding an IPv6 gateway, the destination is `default` and the route script incorrectly consider this is an IPv4 address. As the `addr_family` is used to check the route status, it then report a failure.

**Comment by CAPSLOCK2000** [comment]
I worked around this problem by specifying the destination as a networkaddress:
IPv4: destination="0.0.0.0/0"
IPv6: destination="2000::/3"
That's not exactly the same as 'default' but it should work in most situations.
But not in all, this bug still needs fixing.

I think addr_family should become a configurable parameter, because it's not always possible to determine the correct address family. Eg 'ip route add default dev eth0' is valid for both ipv4 and ipv6.

**Comment by CAPSLOCK2000** [comment]
proposed fix in https://github.com/ClusterLabs/resource-agents/pull/1023
